# This file is autogenerated, don't edit it manually

__version__ = "1.72.1b19971.post10137468.dev169479608"
__scala_version__ = "1.72.1-19971-10137468-169479608-SNAPSHOT"
__spark_version__ = "1.72.0"
