
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-13T15:35:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3687f3734c5a864b399e99c7aa26e180e8830ff6",
 "version": "0.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
