"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dmss_api
from dmss_api.model.access_level import AccessLevel
globals()['AccessLevel'] = AccessLevel
from dmss_api.model.pat_data import PATData


class TestPATData(unittest.TestCase):
    """PATData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPATData(self):
        """Test PATData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PATData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
