"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dmss_api
from dmss_api.model.storage_data_types import StorageDataTypes


class TestStorageDataTypes(unittest.TestCase):
    """StorageDataTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageDataTypes(self):
        """Test StorageDataTypes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageDataTypes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
