"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import dmss_api
from dmss_api.api.blob_api import BlobApi  # noqa: E501


class TestBlobApi(unittest.TestCase):
    """BlobApi unit test stubs"""

    def setUp(self):
        self.api = BlobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_blob_get_by_id(self):
        """Test case for blob_get_by_id

        Get By Id  # noqa: E501
        """
        pass

    def test_blob_upload(self):
        """Test case for blob_upload

        Upload  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
