# Generated by Django 4.2.5 on 2023-09-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0003_alter_human_metadescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='metaTitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
