
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-14T14:08:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c287b3e366786c6de6a610dcc4518bb967dee9cd",
 "version": "2.20.0rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
