#


#


#


#
class BackExceptionMessage:
    GENERIC = 'GENERIC'
    INVALID_TOKEN = 'INVALID_TOKEN'
    ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS'
    ACCOUNT_DOES_NOT_EXIST = 'ACCOUNT_DOES_NOT_EXIST'
    USERNAME_DOES_NOT_EXIST = 'USERNAME_DOES_NOT_EXIST'
    INVALID_PASSWORD = 'INVALID_PASSWORD'
    USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS'
    SERVICE_ALREADY_REGISTERED = 'SERVICE_ALREADY_REGISTERED'
    CHECK_EXECUTED_NOT_FOUND_OR_INVALID = 'CHECK_EXECUTED_NOT_FOUND_OR_INVALID'


