
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-11T21:48:02+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9a168ef9805b9ccb98cad1b17b5c9c4ea79f9b8",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
