# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nymstr',
                'doc_host': 'https://dsm-72.github.io',
                'git_url': 'https://github.com/dsm-72/nymstr',
                'lib_path': 'nymstr'},
  'syms': { 'nymstr.core': { 'nymstr.core.nymstr': ('core.html#nymstr', 'nymstr/core.py'),
                             'nymstr.core.nymstr.__eq__': ('core.html#nymstr.__eq__', 'nymstr/core.py'),
                             'nymstr.core.nymstr.__hash__': ('core.html#nymstr.__hash__', 'nymstr/core.py'),
                             'nymstr.core.nymstr.__init__': ('core.html#nymstr.__init__', 'nymstr/core.py'),
                             'nymstr.core.nymstr.__repr__': ('core.html#nymstr.__repr__', 'nymstr/core.py'),
                             'nymstr.core.nymstr.canon': ('core.html#nymstr.canon', 'nymstr/core.py'),
                             'nymstr.core.nymstr.iscanon': ('core.html#nymstr.iscanon', 'nymstr/core.py'),
                             'nymstr.core.nymstr.isitem': ('core.html#nymstr.isitem', 'nymstr/core.py'),
                             'nymstr.core.nymstr.isknown': ('core.html#nymstr.isknown', 'nymstr/core.py'),
                             'nymstr.core.nymstr.item': ('core.html#nymstr.item', 'nymstr/core.py'),
                             'nymstr.core.nymstr.known': ('core.html#nymstr.known', 'nymstr/core.py'),
                             'nymstr.core.nymstr.snake': ('core.html#nymstr.snake', 'nymstr/core.py')}}}
