
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-14T00:16:53-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c31c2118cdfb1eb55606e59fe741d4c19c83620",
 "version": "v1.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
