# Generated by Django 3.2.4 on 2022-11-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Address Visit',
                'verbose_name_plural': 'Address Visits',
                'permissions': (('can_address', 'Manage Address Visit'),),
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, verbose_name='ip')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Visit Time')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='badi_visit.addressvisit', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'permissions': (('can_visit', 'Manage Visit'),),
            },
        ),
    ]
