
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-11T16:06:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "faed9033ecccc2719e0b1204baef7d593456ccd6",
 "version": "5.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
