
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-15T10:35:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2bade75a068497059279780633891f254a78110",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
