# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.6.7
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

import unittest

import py-scibec-openapi-client
from py-scibec-openapi-client.model.beamline_scope_filter import BeamlineScopeFilter
from py-scibec-openapi-client import configuration


class TestBeamlineScopeFilter(unittest.TestCase):
    """BeamlineScopeFilter unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
