#
from enum import Enum


#


#


#
class DealStatus(Enum):
    OPEN = 'OPEN'
    CLOSE = 'CLOSE'
    DISPUTE = 'DISPUTE'
    WAIT = 'WAIT'
    DONE = 'DONE'
    NONE = 'NONE'


class DealSide(Enum):
    BUY = 'BUY'
    SELL = 'SELL'


class DealAction(Enum):
    NO = 'NO'
    REQUEST = 'REQUEST'
    REJECT_REQUEST = 'REJECT_REQUEST'
    QUOTE = 'QUOTE'
    REJECT_QUOTE = 'REJECT_QUOTE'
    ACCEPT_QUOTE = 'ACCEPT_QUOTE'
    REJECT_TECH_NO_QUOTES = 'REJECT_TECH_NO_QUOTES'
    REJECT_TECH_ANOTHER_SELECTED = 'REJECT_TECH_ANOTHER_SELECTED'
    REJECT_TECH_FORCE = 'REJECT_TECH_FORCE'
    CONFIRM_PAYMENT = 'CONFIRM_PAYMENT'
    CONFIRM_TRANSACTION = 'CONFIRM_TRANSACTION'
    CONFIRM_TRANSACTION_FAILED_FIRST = 'CONFIRM_TRANSACTION_FAILED_FIRST'
    CONFIRM_TRANSACTION_FAILED_SECOND = 'CONFIRM_TRANSACTION_FAILED_SECOND'
    DISPUTE_PAYMENT = 'DISPUTE_PAYMENT'
    USER_DONE = 'USER_DONE'
    DEALER_DONE = 'DEALER_DONE'
    USER_TECH_FORCE_DONE = 'USER_TECH_FORCE_DONE'
    DEALER_TECH_FORCE_DONE = 'DEALER_TECH_FORCE_DONE'
