# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .campaign_message_assign_template_query_resource_object_attributes import (
    CampaignMessageAssignTemplateQueryResourceObjectAttributes,
)
from .campaign_message_assign_template_query_resource_object_relationships import (
    CampaignMessageAssignTemplateQueryResourceObjectRelationships,
)
from .campaign_message_enum import CampaignMessageEnum


class CampaignMessageAssignTemplateQueryResourceObject(pydantic.BaseModel):
    type: CampaignMessageEnum
    attributes: CampaignMessageAssignTemplateQueryResourceObjectAttributes
    relationships: typing.Optional[CampaignMessageAssignTemplateQueryResourceObjectRelationships]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
