# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .catalog_category_bulk_update_job_enum import CatalogCategoryBulkUpdateJobEnum
from .catalog_category_update_job_create_query_resource_object_attributes import (
    CatalogCategoryUpdateJobCreateQueryResourceObjectAttributes,
)


class CatalogCategoryUpdateJobCreateQueryResourceObject(pydantic.BaseModel):
    type: CatalogCategoryBulkUpdateJobEnum
    attributes: CatalogCategoryUpdateJobCreateQueryResourceObjectAttributes

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
