# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class GetUpdateVariantsJobRequestFieldsCatalogVariantItem(str, enum.Enum):
    EXTERNAL_ID = "external_id"
    TITLE = "title"
    DESCRIPTION = "description"
    SKU = "sku"
    INVENTORY_POLICY = "inventory_policy"
    INVENTORY_QUANTITY = "inventory_quantity"
    PRICE = "price"
    URL = "url"
    IMAGE_FULL_URL = "image_full_url"
    IMAGE_THUMBNAIL_URL = "image_thumbnail_url"
    IMAGES = "images"
    CUSTOM_METADATA = "custom_metadata"
    PUBLISHED = "published"
    CREATED = "created"
    UPDATED = "updated"

    def visit(
        self,
        external_id: typing.Callable[[], T_Result],
        title: typing.Callable[[], T_Result],
        description: typing.Callable[[], T_Result],
        sku: typing.Callable[[], T_Result],
        inventory_policy: typing.Callable[[], T_Result],
        inventory_quantity: typing.Callable[[], T_Result],
        price: typing.Callable[[], T_Result],
        url: typing.Callable[[], T_Result],
        image_full_url: typing.Callable[[], T_Result],
        image_thumbnail_url: typing.Callable[[], T_Result],
        images: typing.Callable[[], T_Result],
        custom_metadata: typing.Callable[[], T_Result],
        published: typing.Callable[[], T_Result],
        created: typing.Callable[[], T_Result],
        updated: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.EXTERNAL_ID:
            return external_id()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.TITLE:
            return title()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.DESCRIPTION:
            return description()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.SKU:
            return sku()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.INVENTORY_POLICY:
            return inventory_policy()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.INVENTORY_QUANTITY:
            return inventory_quantity()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.PRICE:
            return price()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.URL:
            return url()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.IMAGE_FULL_URL:
            return image_full_url()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.IMAGE_THUMBNAIL_URL:
            return image_thumbnail_url()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.IMAGES:
            return images()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.CUSTOM_METADATA:
            return custom_metadata()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.PUBLISHED:
            return published()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.CREATED:
            return created()
        if self is GetUpdateVariantsJobRequestFieldsCatalogVariantItem.UPDATED:
            return updated()
