# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class GetFlowMessageRequestIncludeItem(str, enum.Enum):
    FLOW_ACTION = "flow-action"
    TEMPLATE = "template"

    def visit(self, flow_action: typing.Callable[[], T_Result], template: typing.Callable[[], T_Result]) -> T_Result:
        if self is GetFlowMessageRequestIncludeItem.FLOW_ACTION:
            return flow_action()
        if self is GetFlowMessageRequestIncludeItem.TEMPLATE:
            return template()
