# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class GetFlowMessageActionRequestFieldsFlowActionItem(str, enum.Enum):
    ACTION_TYPE = "action_type"
    STATUS = "status"
    CREATED = "created"
    UPDATED = "updated"
    SETTINGS = "settings"
    TRACKING_OPTIONS = "tracking_options"
    SEND_OPTIONS = "send_options"
    SEND_OPTIONS_USE_SMART_SENDING = "send_options.use_smart_sending"
    SEND_OPTIONS_IS_TRANSACTIONAL = "send_options.is_transactional"
    RENDER_OPTIONS = "render_options"
    RENDER_OPTIONS_SHORTEN_LINKS = "render_options.shorten_links"
    RENDER_OPTIONS_ADD_ORG_PREFIX = "render_options.add_org_prefix"
    RENDER_OPTIONS_ADD_INFO_LINK = "render_options.add_info_link"
    RENDER_OPTIONS_ADD_OPT_OUT_LANGUAGE = "render_options.add_opt_out_language"

    def visit(
        self,
        action_type: typing.Callable[[], T_Result],
        status: typing.Callable[[], T_Result],
        created: typing.Callable[[], T_Result],
        updated: typing.Callable[[], T_Result],
        settings: typing.Callable[[], T_Result],
        tracking_options: typing.Callable[[], T_Result],
        send_options: typing.Callable[[], T_Result],
        send_options_use_smart_sending: typing.Callable[[], T_Result],
        send_options_is_transactional: typing.Callable[[], T_Result],
        render_options: typing.Callable[[], T_Result],
        render_options_shorten_links: typing.Callable[[], T_Result],
        render_options_add_org_prefix: typing.Callable[[], T_Result],
        render_options_add_info_link: typing.Callable[[], T_Result],
        render_options_add_opt_out_language: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.ACTION_TYPE:
            return action_type()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.STATUS:
            return status()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.CREATED:
            return created()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.UPDATED:
            return updated()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.SETTINGS:
            return settings()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.TRACKING_OPTIONS:
            return tracking_options()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.SEND_OPTIONS:
            return send_options()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.SEND_OPTIONS_USE_SMART_SENDING:
            return send_options_use_smart_sending()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.SEND_OPTIONS_IS_TRANSACTIONAL:
            return send_options_is_transactional()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.RENDER_OPTIONS:
            return render_options()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.RENDER_OPTIONS_SHORTEN_LINKS:
            return render_options_shorten_links()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.RENDER_OPTIONS_ADD_ORG_PREFIX:
            return render_options_add_org_prefix()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.RENDER_OPTIONS_ADD_INFO_LINK:
            return render_options_add_info_link()
        if self is GetFlowMessageActionRequestFieldsFlowActionItem.RENDER_OPTIONS_ADD_OPT_OUT_LANGUAGE:
            return render_options_add_opt_out_language()
