# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class GetEventProfileRequestFieldsProfileItem(str, enum.Enum):
    EMAIL = "email"
    PHONE_NUMBER = "phone_number"
    EXTERNAL_ID = "external_id"
    FIRST_NAME = "first_name"
    LAST_NAME = "last_name"
    ORGANIZATION = "organization"
    TITLE = "title"
    IMAGE = "image"
    CREATED = "created"
    UPDATED = "updated"
    LAST_EVENT_DATE = "last_event_date"
    LOCATION = "location"
    LOCATION_ADDRESS_1 = "location.address1"
    LOCATION_ADDRESS_2 = "location.address2"
    LOCATION_CITY = "location.city"
    LOCATION_COUNTRY = "location.country"
    LOCATION_LATITUDE = "location.latitude"
    LOCATION_LONGITUDE = "location.longitude"
    LOCATION_REGION = "location.region"
    LOCATION_ZIP = "location.zip"
    LOCATION_TIMEZONE = "location.timezone"
    PROPERTIES = "properties"
    SUBSCRIPTIONS = "subscriptions"
    SUBSCRIPTIONS_EMAIL = "subscriptions.email"
    SUBSCRIPTIONS_EMAIL_MARKETING = "subscriptions.email.marketing"
    SUBSCRIPTIONS_EMAIL_MARKETING_CONSENT = "subscriptions.email.marketing.consent"
    SUBSCRIPTIONS_EMAIL_MARKETING_TIMESTAMP = "subscriptions.email.marketing.timestamp"
    SUBSCRIPTIONS_EMAIL_MARKETING_METHOD = "subscriptions.email.marketing.method"
    SUBSCRIPTIONS_EMAIL_MARKETING_METHOD_DETAIL = "subscriptions.email.marketing.method_detail"
    SUBSCRIPTIONS_EMAIL_MARKETING_CUSTOM_METHOD_DETAIL = "subscriptions.email.marketing.custom_method_detail"
    SUBSCRIPTIONS_EMAIL_MARKETING_DOUBLE_OPTIN = "subscriptions.email.marketing.double_optin"
    SUBSCRIPTIONS_EMAIL_MARKETING_SUPPRESSIONS = "subscriptions.email.marketing.suppressions"
    SUBSCRIPTIONS_EMAIL_MARKETING_LIST_SUPPRESSIONS = "subscriptions.email.marketing.list_suppressions"
    SUBSCRIPTIONS_SMS = "subscriptions.sms"
    SUBSCRIPTIONS_SMS_MARKETING = "subscriptions.sms.marketing"
    SUBSCRIPTIONS_SMS_MARKETING_CONSENT = "subscriptions.sms.marketing.consent"
    SUBSCRIPTIONS_SMS_MARKETING_TIMESTAMP = "subscriptions.sms.marketing.timestamp"
    SUBSCRIPTIONS_SMS_MARKETING_METHOD = "subscriptions.sms.marketing.method"
    SUBSCRIPTIONS_SMS_MARKETING_METHOD_DETAIL = "subscriptions.sms.marketing.method_detail"
    PREDICTIVE_ANALYTICS = "predictive_analytics"
    PREDICTIVE_ANALYTICS_HISTORIC_CLV = "predictive_analytics.historic_clv"
    PREDICTIVE_ANALYTICS_PREDICTED_CLV = "predictive_analytics.predicted_clv"
    PREDICTIVE_ANALYTICS_TOTAL_CLV = "predictive_analytics.total_clv"
    PREDICTIVE_ANALYTICS_HISTORIC_NUMBER_OF_ORDERS = "predictive_analytics.historic_number_of_orders"
    PREDICTIVE_ANALYTICS_PREDICTED_NUMBER_OF_ORDERS = "predictive_analytics.predicted_number_of_orders"
    PREDICTIVE_ANALYTICS_AVERAGE_DAYS_BETWEEN_ORDERS = "predictive_analytics.average_days_between_orders"
    PREDICTIVE_ANALYTICS_AVERAGE_ORDER_VALUE = "predictive_analytics.average_order_value"
    PREDICTIVE_ANALYTICS_CHURN_PROBABILITY = "predictive_analytics.churn_probability"
    PREDICTIVE_ANALYTICS_EXPECTED_DATE_OF_NEXT_ORDER = "predictive_analytics.expected_date_of_next_order"

    def visit(
        self,
        email: typing.Callable[[], T_Result],
        phone_number: typing.Callable[[], T_Result],
        external_id: typing.Callable[[], T_Result],
        first_name: typing.Callable[[], T_Result],
        last_name: typing.Callable[[], T_Result],
        organization: typing.Callable[[], T_Result],
        title: typing.Callable[[], T_Result],
        image: typing.Callable[[], T_Result],
        created: typing.Callable[[], T_Result],
        updated: typing.Callable[[], T_Result],
        last_event_date: typing.Callable[[], T_Result],
        location: typing.Callable[[], T_Result],
        location_address_1: typing.Callable[[], T_Result],
        location_address_2: typing.Callable[[], T_Result],
        location_city: typing.Callable[[], T_Result],
        location_country: typing.Callable[[], T_Result],
        location_latitude: typing.Callable[[], T_Result],
        location_longitude: typing.Callable[[], T_Result],
        location_region: typing.Callable[[], T_Result],
        location_zip: typing.Callable[[], T_Result],
        location_timezone: typing.Callable[[], T_Result],
        properties: typing.Callable[[], T_Result],
        subscriptions: typing.Callable[[], T_Result],
        subscriptions_email: typing.Callable[[], T_Result],
        subscriptions_email_marketing: typing.Callable[[], T_Result],
        subscriptions_email_marketing_consent: typing.Callable[[], T_Result],
        subscriptions_email_marketing_timestamp: typing.Callable[[], T_Result],
        subscriptions_email_marketing_method: typing.Callable[[], T_Result],
        subscriptions_email_marketing_method_detail: typing.Callable[[], T_Result],
        subscriptions_email_marketing_custom_method_detail: typing.Callable[[], T_Result],
        subscriptions_email_marketing_double_optin: typing.Callable[[], T_Result],
        subscriptions_email_marketing_suppressions: typing.Callable[[], T_Result],
        subscriptions_email_marketing_list_suppressions: typing.Callable[[], T_Result],
        subscriptions_sms: typing.Callable[[], T_Result],
        subscriptions_sms_marketing: typing.Callable[[], T_Result],
        subscriptions_sms_marketing_consent: typing.Callable[[], T_Result],
        subscriptions_sms_marketing_timestamp: typing.Callable[[], T_Result],
        subscriptions_sms_marketing_method: typing.Callable[[], T_Result],
        subscriptions_sms_marketing_method_detail: typing.Callable[[], T_Result],
        predictive_analytics: typing.Callable[[], T_Result],
        predictive_analytics_historic_clv: typing.Callable[[], T_Result],
        predictive_analytics_predicted_clv: typing.Callable[[], T_Result],
        predictive_analytics_total_clv: typing.Callable[[], T_Result],
        predictive_analytics_historic_number_of_orders: typing.Callable[[], T_Result],
        predictive_analytics_predicted_number_of_orders: typing.Callable[[], T_Result],
        predictive_analytics_average_days_between_orders: typing.Callable[[], T_Result],
        predictive_analytics_average_order_value: typing.Callable[[], T_Result],
        predictive_analytics_churn_probability: typing.Callable[[], T_Result],
        predictive_analytics_expected_date_of_next_order: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is GetEventProfileRequestFieldsProfileItem.EMAIL:
            return email()
        if self is GetEventProfileRequestFieldsProfileItem.PHONE_NUMBER:
            return phone_number()
        if self is GetEventProfileRequestFieldsProfileItem.EXTERNAL_ID:
            return external_id()
        if self is GetEventProfileRequestFieldsProfileItem.FIRST_NAME:
            return first_name()
        if self is GetEventProfileRequestFieldsProfileItem.LAST_NAME:
            return last_name()
        if self is GetEventProfileRequestFieldsProfileItem.ORGANIZATION:
            return organization()
        if self is GetEventProfileRequestFieldsProfileItem.TITLE:
            return title()
        if self is GetEventProfileRequestFieldsProfileItem.IMAGE:
            return image()
        if self is GetEventProfileRequestFieldsProfileItem.CREATED:
            return created()
        if self is GetEventProfileRequestFieldsProfileItem.UPDATED:
            return updated()
        if self is GetEventProfileRequestFieldsProfileItem.LAST_EVENT_DATE:
            return last_event_date()
        if self is GetEventProfileRequestFieldsProfileItem.LOCATION:
            return location()
        if self is GetEventProfileRequestFieldsProfileItem.LOCATION_ADDRESS_1:
            return location_address_1()
        if self is GetEventProfileRequestFieldsProfileItem.LOCATION_ADDRESS_2:
            return location_address_2()
        if self is GetEventProfileRequestFieldsProfileItem.LOCATION_CITY:
            return location_city()
        if self is GetEventProfileRequestFieldsProfileItem.LOCATION_COUNTRY:
            return location_country()
        if self is GetEventProfileRequestFieldsProfileItem.LOCATION_LATITUDE:
            return location_latitude()
        if self is GetEventProfileRequestFieldsProfileItem.LOCATION_LONGITUDE:
            return location_longitude()
        if self is GetEventProfileRequestFieldsProfileItem.LOCATION_REGION:
            return location_region()
        if self is GetEventProfileRequestFieldsProfileItem.LOCATION_ZIP:
            return location_zip()
        if self is GetEventProfileRequestFieldsProfileItem.LOCATION_TIMEZONE:
            return location_timezone()
        if self is GetEventProfileRequestFieldsProfileItem.PROPERTIES:
            return properties()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS:
            return subscriptions()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_EMAIL:
            return subscriptions_email()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_EMAIL_MARKETING:
            return subscriptions_email_marketing()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_EMAIL_MARKETING_CONSENT:
            return subscriptions_email_marketing_consent()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_EMAIL_MARKETING_TIMESTAMP:
            return subscriptions_email_marketing_timestamp()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_EMAIL_MARKETING_METHOD:
            return subscriptions_email_marketing_method()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_EMAIL_MARKETING_METHOD_DETAIL:
            return subscriptions_email_marketing_method_detail()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_EMAIL_MARKETING_CUSTOM_METHOD_DETAIL:
            return subscriptions_email_marketing_custom_method_detail()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_EMAIL_MARKETING_DOUBLE_OPTIN:
            return subscriptions_email_marketing_double_optin()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_EMAIL_MARKETING_SUPPRESSIONS:
            return subscriptions_email_marketing_suppressions()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_EMAIL_MARKETING_LIST_SUPPRESSIONS:
            return subscriptions_email_marketing_list_suppressions()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_SMS:
            return subscriptions_sms()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_SMS_MARKETING:
            return subscriptions_sms_marketing()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_SMS_MARKETING_CONSENT:
            return subscriptions_sms_marketing_consent()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_SMS_MARKETING_TIMESTAMP:
            return subscriptions_sms_marketing_timestamp()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_SMS_MARKETING_METHOD:
            return subscriptions_sms_marketing_method()
        if self is GetEventProfileRequestFieldsProfileItem.SUBSCRIPTIONS_SMS_MARKETING_METHOD_DETAIL:
            return subscriptions_sms_marketing_method_detail()
        if self is GetEventProfileRequestFieldsProfileItem.PREDICTIVE_ANALYTICS:
            return predictive_analytics()
        if self is GetEventProfileRequestFieldsProfileItem.PREDICTIVE_ANALYTICS_HISTORIC_CLV:
            return predictive_analytics_historic_clv()
        if self is GetEventProfileRequestFieldsProfileItem.PREDICTIVE_ANALYTICS_PREDICTED_CLV:
            return predictive_analytics_predicted_clv()
        if self is GetEventProfileRequestFieldsProfileItem.PREDICTIVE_ANALYTICS_TOTAL_CLV:
            return predictive_analytics_total_clv()
        if self is GetEventProfileRequestFieldsProfileItem.PREDICTIVE_ANALYTICS_HISTORIC_NUMBER_OF_ORDERS:
            return predictive_analytics_historic_number_of_orders()
        if self is GetEventProfileRequestFieldsProfileItem.PREDICTIVE_ANALYTICS_PREDICTED_NUMBER_OF_ORDERS:
            return predictive_analytics_predicted_number_of_orders()
        if self is GetEventProfileRequestFieldsProfileItem.PREDICTIVE_ANALYTICS_AVERAGE_DAYS_BETWEEN_ORDERS:
            return predictive_analytics_average_days_between_orders()
        if self is GetEventProfileRequestFieldsProfileItem.PREDICTIVE_ANALYTICS_AVERAGE_ORDER_VALUE:
            return predictive_analytics_average_order_value()
        if self is GetEventProfileRequestFieldsProfileItem.PREDICTIVE_ANALYTICS_CHURN_PROBABILITY:
            return predictive_analytics_churn_probability()
        if self is GetEventProfileRequestFieldsProfileItem.PREDICTIVE_ANALYTICS_EXPECTED_DATE_OF_NEXT_ORDER:
            return predictive_analytics_expected_date_of_next_order()
