# This file was auto-generated by Fern from our API Definition.

import typing

from .email_tracking_options_sub_object import EmailTrackingOptionsSubObject
from .sms_tracking_options_sub_object import SmsTrackingOptionsSubObject

PostCampaignResponseDataAttributesTrackingOptions = typing.Union[
    EmailTrackingOptionsSubObject, SmsTrackingOptionsSubObject
]
