
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-16T15:10:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "feebcd64355f918c01b5035057b11af0f2647a76",
 "version": "0.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
