
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-11T13:22:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9f610e80cd08f3e24257f7e5411ea5d15f5959e",
 "version": "2.19.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
