# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/multisig/v1/multisig.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='decimal/multisig/v1/multisig.proto',
  package='decimal.multisig.v1',
  syntax='proto3',
  serialized_options=b'\n\027com.decimal.multisig.v1B\rMultisigProtoP\001Z8bitbucket.org/decimalteam/go-smart-node/x/multisig/types\242\002\003DMX\252\002\023Decimal.Multisig.V1\312\002\023Decimal\\Multisig\\V1\342\002\037Decimal\\Multisig\\V1\\GPBMetadata\352\002\025Decimal::Multisig::V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"decimal/multisig/v1/multisig.proto\x12\x13\x64\x65\x63imal.multisig.v1\x1a\x14gogoproto/gogo.proto\x1a\x19google/protobuf/any.proto\x1a\x19\x63osmos_proto/cosmos.proto\"\x9a\x01\n\x06Wallet\x12\x32\n\x07\x61\x64\x64ress\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x07\x61\x64\x64ress\x12\x16\n\x06owners\x18\x02 \x03(\tR\x06owners\x12\x18\n\x07weights\x18\x03 \x03(\rR\x07weights\x12\x1c\n\tthreshold\x18\x04 \x01(\rR\tthreshold:\x0c\x88\xa0\x1f\x00\x98\xa0\x1f\x01\xe8\xa0\x1f\x01\"\xbd\x01\n\x0bTransaction\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x30\n\x06wallet\x18\x02 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x06wallet\x12?\n\x07message\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyB\x0f\xc8\xde\x1f\x00\xca\xb4-\x07sdk.MsgR\x07message\x12\x1d\n\ncreated_at\x18\x04 \x01(\x03R\tcreatedAt:\x0c\x88\xa0\x1f\x00\x98\xa0\x1f\x01\xe8\xa0\x1f\x01\x42\xd0\x01\n\x17\x63om.decimal.multisig.v1B\rMultisigProtoP\x01Z8bitbucket.org/decimalteam/go-smart-node/x/multisig/types\xa2\x02\x03\x44MX\xaa\x02\x13\x44\x65\x63imal.Multisig.V1\xca\x02\x13\x44\x65\x63imal\\Multisig\\V1\xe2\x02\x1f\x44\x65\x63imal\\Multisig\\V1\\GPBMetadata\xea\x02\x15\x44\x65\x63imal::Multisig::V1b\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,cosmos__proto_dot_cosmos__pb2.DESCRIPTOR,])




_WALLET = _descriptor.Descriptor(
  name='Wallet',
  full_name='decimal.multisig.v1.Wallet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='decimal.multisig.v1.Wallet.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\322\264-\024cosmos.AddressString', json_name='address', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owners', full_name='decimal.multisig.v1.Wallet.owners', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='owners', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weights', full_name='decimal.multisig.v1.Wallet.weights', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='weights', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='decimal.multisig.v1.Wallet.threshold', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='threshold', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\210\240\037\000\230\240\037\001\350\240\037\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=290,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='decimal.multisig.v1.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='decimal.multisig.v1.Transaction.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wallet', full_name='decimal.multisig.v1.Transaction.wallet', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\322\264-\024cosmos.AddressString', json_name='wallet', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='decimal.multisig.v1.Transaction.message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000\312\264-\007sdk.Msg', json_name='message', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='decimal.multisig.v1.Transaction.created_at', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='createdAt', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\210\240\037\000\230\240\037\001\350\240\037\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=482,
)

_TRANSACTION.fields_by_name['message'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['Wallet'] = _WALLET
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Wallet = _reflection.GeneratedProtocolMessageType('Wallet', (_message.Message,), {
  'DESCRIPTOR' : _WALLET,
  '__module__' : 'decimal.multisig.v1.multisig_pb2'
  # @@protoc_insertion_point(class_scope:decimal.multisig.v1.Wallet)
  })
_sym_db.RegisterMessage(Wallet)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'decimal.multisig.v1.multisig_pb2'
  # @@protoc_insertion_point(class_scope:decimal.multisig.v1.Transaction)
  })
_sym_db.RegisterMessage(Transaction)


DESCRIPTOR._options = None
_WALLET.fields_by_name['address']._options = None
_WALLET._options = None
_TRANSACTION.fields_by_name['wallet']._options = None
_TRANSACTION.fields_by_name['message']._options = None
_TRANSACTION._options = None
# @@protoc_insertion_point(module_scope)
