# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.api.metadata_providers_provider_api import MetadataProvidersProviderApi  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestMetadataProvidersProviderApi(unittest.TestCase):
    """MetadataProvidersProviderApi unit test stubs"""

    def setUp(self):
        self.api = MetadataProvidersProviderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_metadata_providers_all_get(self):
        """Test case for api_metadata_providers_all_get

        Get a list of providers.  # noqa: E501
        """
        pass

    def test_api_metadata_providers_deploy_id_provider_put(self):
        """Test case for api_metadata_providers_deploy_id_provider_put

        Update the entities of this provider to allow deploy them in the next data ingestion execution  # noqa: E501
        """
        pass

    def test_api_metadata_providers_export_post(self):
        """Test case for api_metadata_providers_export_post

        Starts the transfer of part of the Data Catalog to another Sidra deployment.  This method must be executed on the source environment.  # noqa: E501
        """
        pass

    def test_api_metadata_providers_get(self):
        """Test case for api_metadata_providers_get

        Gets a list of Providers filtered  # noqa: E501
        """
        pass

    def test_api_metadata_providers_id_basicinfo_get(self):
        """Test case for api_metadata_providers_id_basicinfo_get

        Get a Providers by id. Only basic info will be retrieved. To get other info related, use another method.  # noqa: E501
        """
        pass

    def test_api_metadata_providers_id_dataintakeprocesses_get(self):
        """Test case for api_metadata_providers_id_dataintakeprocesses_get

        Get all the DataIntakeProcess related to the Provider  # noqa: E501
        """
        pass

    def test_api_metadata_providers_id_delete(self):
        """Test case for api_metadata_providers_id_delete

        Delete a specific Provider  # noqa: E501
        """
        pass

    def test_api_metadata_providers_id_delete_entities_delete(self):
        """Test case for api_metadata_providers_id_delete_entities_delete

        Delete provider entities related to server name and db passed as parameters  # noqa: E501
        """
        pass

    def test_api_metadata_providers_id_get(self):
        """Test case for api_metadata_providers_id_get

        Get a Providers by id  # noqa: E501
        """
        pass

    def test_api_metadata_providers_id_patch(self):
        """Test case for api_metadata_providers_id_patch

        Update Partial Provider  # noqa: E501
        """
        pass

    def test_api_metadata_providers_id_put(self):
        """Test case for api_metadata_providers_id_put

        Updates a Providers by id  # noqa: E501
        """
        pass

    def test_api_metadata_providers_import_post(self):
        """Test case for api_metadata_providers_import_post

        Imports the part of the Data Catalog exported by transfer method   This method must be executed on the destination environment.  # noqa: E501
        """
        pass

    def test_api_metadata_providers_name_get(self):
        """Test case for api_metadata_providers_name_get

        Get a Provider by name  # noqa: E501
        """
        pass

    def test_api_metadata_providers_post(self):
        """Test case for api_metadata_providers_post

        Creates a Providers  # noqa: E501
        """
        pass

    def test_api_metadata_providers_provider_id_tags_get(self):
        """Test case for api_metadata_providers_provider_id_tags_get

        Gets tag of this provider  # noqa: E501
        """
        pass

    def test_api_metadata_providers_provider_id_tags_post(self):
        """Test case for api_metadata_providers_provider_id_tags_post

        Adds tag to this provider  # noqa: E501
        """
        pass

    def test_api_metadata_providers_provider_id_tags_tag_id_delete(self):
        """Test case for api_metadata_providers_provider_id_tags_tag_id_delete

        Removes tag to this provider  # noqa: E501
        """
        pass

    def test_api_metadata_providers_providerswithentititesbypipelinetemplatetype_get(self):
        """Test case for api_metadata_providers_providerswithentititesbypipelinetemplatetype_get

        Get all providers and their respective entities  # noqa: E501
        """
        pass

    def test_api_metadata_providers_raw_post(self):
        """Test case for api_metadata_providers_raw_post

        Creates a Provider using untransformed entity  # noqa: E501
        """
        pass

    def test_transfer_status_route(self):
        """Test case for transfer_status_route

        Gets the information of the execution status of a transfer query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
