# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.api.ingestion_ingestion_api import IngestionIngestionApi  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestIngestionIngestionApi(unittest.TestCase):
    """IngestionIngestionApi unit test stubs"""

    def setUp(self):
        self.api = IngestionIngestionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_ingestion_asset_asset_id_loaded_post(self):
        """Test case for api_ingestion_asset_asset_id_loaded_post

        Updates ValidationErrors and Entities fields, representing the number of validation errors and entities in an asset.  Status of the Asset is set to MovedToDataStorageUnit  # noqa: E501
        """
        pass

    def test_api_ingestion_loadasset_post(self):
        """Test case for api_ingestion_loadasset_post

        Registers an asset from the Landing Zone  # noqa: E501
        """
        pass

    def test_api_ingestion_registerasset_post(self):
        """Test case for api_ingestion_registerasset_post

        Registers an asset from the Landing Zone  # noqa: E501
        """
        pass

    def test_api_ingestion_registerinfo_post(self):
        """Test case for api_ingestion_registerinfo_post

        Registers an asset from the Landing Zone  # noqa: E501
        """
        pass

    def test_api_ingestion_registersetassets_post(self):
        """Test case for api_ingestion_registersetassets_post

        Registers a set of assets  # noqa: E501
        """
        pass

    def test_api_ingestion_storage_landing_get(self):
        """Test case for api_ingestion_storage_landing_get

        Gets the landing paths availables to upload the asset provided.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
