# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.api.data_factory_triggers_triggers_api import DataFactoryTriggersTriggersApi  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestDataFactoryTriggersTriggersApi(unittest.TestCase):
    """DataFactoryTriggersTriggersApi unit test stubs"""

    def setUp(self):
        self.api = DataFactoryTriggersTriggersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_datafactory_triggers_get(self):
        """Test case for api_datafactory_triggers_get

        Gets a list of triggers filtered  # noqa: E501
        """
        pass

    def test_api_datafactory_triggers_get_all_by_template_type_async_id_trigger_template_type_get(self):
        """Test case for api_datafactory_triggers_get_all_by_template_type_async_id_trigger_template_type_get

        Gets a list of triggers by template type  # noqa: E501
        """
        pass

    def test_api_datafactory_triggers_id_delete(self):
        """Test case for api_datafactory_triggers_id_delete

        Delete a specific Trigger  # noqa: E501
        """
        pass

    def test_api_datafactory_triggers_id_put(self):
        """Test case for api_datafactory_triggers_id_put

        Updates a trigger by id  # noqa: E501
        """
        pass

    def test_api_datafactory_triggers_id_trigger_pipelines_get(self):
        """Test case for api_datafactory_triggers_id_trigger_pipelines_get

        Get all pipelines associated with the specific Trigger  # noqa: E501
        """
        pass

    def test_api_datafactory_triggers_id_trigger_pipelines_id_pipeline_delete(self):
        """Test case for api_datafactory_triggers_id_trigger_pipelines_id_pipeline_delete

        Delete the association of the Pipeline with the Trigger  # noqa: E501
        """
        pass

    def test_api_datafactory_triggers_id_trigger_pipelines_id_pipeline_post(self):
        """Test case for api_datafactory_triggers_id_trigger_pipelines_id_pipeline_post

        Associate a Pipeline with a Trigger  # noqa: E501
        """
        pass

    def test_api_datafactory_triggers_item_id_post(self):
        """Test case for api_datafactory_triggers_item_id_post

        Update trigger definition  # noqa: E501
        """
        pass

    def test_api_datafactory_triggers_pipeline_template_name_parameters_get(self):
        """Test case for api_datafactory_triggers_pipeline_template_name_parameters_get

        Get parameters needed for a specific trigger template name  # noqa: E501
        """
        pass

    def test_api_datafactory_triggers_post(self):
        """Test case for api_datafactory_triggers_post

        Creates a trigger  # noqa: E501
        """
        pass

    def test_get_trigger_by_id_async(self):
        """Test case for get_trigger_by_id_async

        Get a trigger by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
