# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.api.data_storage_unit_landing_zones_landing_zones_api import DataStorageUnitLandingZonesLandingZonesApi  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestDataStorageUnitLandingZonesLandingZonesApi(unittest.TestCase):
    """DataStorageUnitLandingZonesLandingZonesApi unit test stubs"""

    def setUp(self):
        self.api = DataStorageUnitLandingZonesLandingZonesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_datastorageunit_landing_zones_get(self):
        """Test case for api_datastorageunit_landing_zones_get

        Gets a list of Landing Zones filtered  # noqa: E501
        """
        pass

    def test_api_datastorageunit_landing_zones_id_delete(self):
        """Test case for api_datastorageunit_landing_zones_id_delete

        Delete a specific LandingZone  # noqa: E501
        """
        pass

    def test_api_datastorageunit_landing_zones_id_get(self):
        """Test case for api_datastorageunit_landing_zones_id_get

        Get a Landing Zone by id  # noqa: E501
        """
        pass

    def test_api_datastorageunit_landing_zones_id_put(self):
        """Test case for api_datastorageunit_landing_zones_id_put

        Updates a Landing Zone by id  # noqa: E501
        """
        pass

    def test_api_datastorageunit_landing_zones_post(self):
        """Test case for api_datastorageunit_landing_zones_post

        Creates a Landing Zone  # noqa: E501
        """
        pass

    def test_api_datastorageunit_landing_zones_tokens_get(self):
        """Test case for api_datastorageunit_landing_zones_tokens_get

        Gets the landing paths availables to upload the asset provided.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
