# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/fee/v1/tx.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from decimal.fee.v1 import fee_pb2 as decimal_dot_fee_dot_v1_dot_fee__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='decimal/fee/v1/tx.proto',
  package='decimal.fee.v1',
  syntax='proto3',
  serialized_options=b'\n\022com.decimal.fee.v1B\007TxProtoP\001Z3bitbucket.org/decimalteam/go-smart-node/x/fee/types\242\002\003DFX\252\002\016Decimal.Fee.V1\312\002\016Decimal\\Fee\\V1\342\002\032Decimal\\Fee\\V1\\GPBMetadata\352\002\020Decimal::Fee::V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x64\x65\x63imal/fee/v1/tx.proto\x12\x0e\x64\x65\x63imal.fee.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x18\x64\x65\x63imal/fee/v1/fee.proto\"\x8d\x01\n\x13MsgUpdateCoinPrices\x12\x30\n\x06oracle\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x06oracle\x12\x37\n\x06prices\x18\x02 \x03(\x0b\x32\x19.decimal.fee.v1.CoinPriceB\x04\xc8\xde\x1f\x00R\x06prices:\x0b\x82\xe7\xb0*\x06oracle\"\x1d\n\x1bMsgUpdateCoinPricesResponse2k\n\x03Msg\x12\x64\n\x10UpdateCoinPrices\x12#.decimal.fee.v1.MsgUpdateCoinPrices\x1a+.decimal.fee.v1.MsgUpdateCoinPricesResponseB\xac\x01\n\x12\x63om.decimal.fee.v1B\x07TxProtoP\x01Z3bitbucket.org/decimalteam/go-smart-node/x/fee/types\xa2\x02\x03\x44\x46X\xaa\x02\x0e\x44\x65\x63imal.Fee.V1\xca\x02\x0e\x44\x65\x63imal\\Fee\\V1\xe2\x02\x1a\x44\x65\x63imal\\Fee\\V1\\GPBMetadata\xea\x02\x10\x44\x65\x63imal::Fee::V1b\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos__proto_dot_cosmos__pb2.DESCRIPTOR,cosmos_dot_msg_dot_v1_dot_msg__pb2.DESCRIPTOR,decimal_dot_fee_dot_v1_dot_fee__pb2.DESCRIPTOR,])




_MSGUPDATECOINPRICES = _descriptor.Descriptor(
  name='MsgUpdateCoinPrices',
  full_name='decimal.fee.v1.MsgUpdateCoinPrices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='oracle', full_name='decimal.fee.v1.MsgUpdateCoinPrices.oracle', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\322\264-\024cosmos.AddressString', json_name='oracle', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prices', full_name='decimal.fee.v1.MsgUpdateCoinPrices.prices', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', json_name='prices', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\202\347\260*\006oracle',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=285,
)


_MSGUPDATECOINPRICESRESPONSE = _descriptor.Descriptor(
  name='MsgUpdateCoinPricesResponse',
  full_name='decimal.fee.v1.MsgUpdateCoinPricesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=316,
)

_MSGUPDATECOINPRICES.fields_by_name['prices'].message_type = decimal_dot_fee_dot_v1_dot_fee__pb2._COINPRICE
DESCRIPTOR.message_types_by_name['MsgUpdateCoinPrices'] = _MSGUPDATECOINPRICES
DESCRIPTOR.message_types_by_name['MsgUpdateCoinPricesResponse'] = _MSGUPDATECOINPRICESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgUpdateCoinPrices = _reflection.GeneratedProtocolMessageType('MsgUpdateCoinPrices', (_message.Message,), {
  'DESCRIPTOR' : _MSGUPDATECOINPRICES,
  '__module__' : 'decimal.fee.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:decimal.fee.v1.MsgUpdateCoinPrices)
  })
_sym_db.RegisterMessage(MsgUpdateCoinPrices)

MsgUpdateCoinPricesResponse = _reflection.GeneratedProtocolMessageType('MsgUpdateCoinPricesResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGUPDATECOINPRICESRESPONSE,
  '__module__' : 'decimal.fee.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:decimal.fee.v1.MsgUpdateCoinPricesResponse)
  })
_sym_db.RegisterMessage(MsgUpdateCoinPricesResponse)


DESCRIPTOR._options = None
_MSGUPDATECOINPRICES.fields_by_name['oracle']._options = None
_MSGUPDATECOINPRICES.fields_by_name['prices']._options = None
_MSGUPDATECOINPRICES._options = None

_MSG = _descriptor.ServiceDescriptor(
  name='Msg',
  full_name='decimal.fee.v1.Msg',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=318,
  serialized_end=425,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateCoinPrices',
    full_name='decimal.fee.v1.Msg.UpdateCoinPrices',
    index=0,
    containing_service=None,
    input_type=_MSGUPDATECOINPRICES,
    output_type=_MSGUPDATECOINPRICESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name['Msg'] = _MSG

# @@protoc_insertion_point(module_scope)
