
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-13T18:09:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fcb9ebbcacacf97a5a83fc56c77048f745432e3c",
 "version": "2023.9.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
