set(_CATKIN_CURRENT_PACKAGE "mobile_message_service_generator")
set(mobile_message_service_generator_VERSION "0.4.0")
set(mobile_message_service_generator_MAINTAINER "Ronaldson Bellande <ronaldsonbellande@gmail.com>")
set(mobile_message_service_generator_PACKAGE_FORMAT "1")
set(mobile_message_service_generator_BUILD_DEPENDS "genmsg" "mobile_catkin_modules_build_development_tools" "python-catkin-pkg" "python-rospkg" "rosmobile_bootstrap" "mobile_catkin_modules_build_development_tools")
set(mobile_message_service_generator_BUILD_EXPORT_DEPENDS "genmsg" "mobile_catkin_modules_build_development_tools" "python-catkin-pkg" "python-rospkg" "rosmobile_bootstrap" "mobile_catkin_modules_build_development_tools")
set(mobile_message_service_generator_BUILDTOOL_DEPENDS "catkin")
set(mobile_message_service_generator_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(mobile_message_service_generator_BUILDTOOL_EXPORT_DEPENDS )
set(mobile_message_service_generator_EXEC_DEPENDS "genmsg" "mobile_catkin_modules_build_development_tools" "python-catkin-pkg" "python-rospkg" "rosmobile_bootstrap" "mobile_catkin_modules_build_development_tools")
set(mobile_message_service_generator_RUN_DEPENDS "genmsg" "mobile_catkin_modules_build_development_tools" "python-catkin-pkg" "python-rospkg" "rosmobile_bootstrap")
set(mobile_message_service_generator_TEST_DEPENDS )
set(mobile_message_service_generator_DOC_DEPENDS )
set(mobile_message_service_generator_URL_WEBSITE "http://www.ros.org/wiki/mobile_message_service_generator")
set(mobile_message_service_generator_URL_BUGTRACKER "https://github.com/rosmobile/mobile_message_service_generator/issues")
set(mobile_message_service_generator_URL_REPOSITORY "https://github.com/rosmobile/mobile_message_service_generator")
set(mobile_message_service_generator_DEPRECATED "")