
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-15T15:41:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1319a3d66e9cb0d359d62c3af13b2a11ad65f74d",
 "version": "0.3.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
