def test_import():
    import nr_metadata  # noqa
    import nr_metadata.common  # noqa
    import nr_metadata.common.config  # noqa
    import nr_metadata.common.ext  # noqa
    import nr_metadata.common.models  # noqa
    import nr_metadata.common.proxies  # noqa
    import nr_metadata.common.records  # noqa
    import nr_metadata.common.records.api  # noqa
    import nr_metadata.common.records.dumper  # noqa
    import nr_metadata.common.records.jsonschemas  # noqa
    import nr_metadata.common.records.mappings  # noqa
    import nr_metadata.common.records.models  # noqa
    import nr_metadata.common.records.multilingual_dumper  # noqa
    import nr_metadata.common.resources  # noqa
    import nr_metadata.common.resources.records  # noqa
    import nr_metadata.common.resources.records.config  # noqa
    import nr_metadata.common.resources.records.resource  # noqa
    import nr_metadata.common.resources.records.ui  # noqa
    import nr_metadata.common.services  # noqa
    import nr_metadata.common.services.records  # noqa
    import nr_metadata.common.services.records.config  # noqa
    import nr_metadata.common.services.records.facets  # noqa
    import nr_metadata.common.services.records.permissions  # noqa
    import nr_metadata.common.services.records.schema_common  # noqa
    import nr_metadata.common.services.records.schema_datatypes  # noqa
    import nr_metadata.common.services.records.search  # noqa
    import nr_metadata.common.services.records.service  # noqa
    import nr_metadata.common.services.records.ui_schema_common  # noqa
    import nr_metadata.common.services.records.ui_schema_datatypes  # noqa
    import nr_metadata.common.version  # noqa
    import nr_metadata.common.views  # noqa
    import nr_metadata.common.views.records  # noqa
    import nr_metadata.common.views.records.api  # noqa
    import nr_metadata.common.views.records.app  # noqa
    import nr_metadata.documents  # noqa
    import nr_metadata.documents.config  # noqa
    import nr_metadata.documents.ext  # noqa
    import nr_metadata.documents.models  # noqa
    import nr_metadata.documents.proxies  # noqa
    import nr_metadata.documents.records  # noqa
    import nr_metadata.documents.records.api  # noqa
    import nr_metadata.documents.records.dumper  # noqa
    import nr_metadata.documents.records.jsonschemas  # noqa
    import nr_metadata.documents.records.mappings  # noqa
    import nr_metadata.documents.records.models  # noqa
    import nr_metadata.documents.records.multilingual_dumper  # noqa
    import nr_metadata.documents.resources  # noqa
    import nr_metadata.documents.resources.records  # noqa
    import nr_metadata.documents.resources.records.config  # noqa
    import nr_metadata.documents.resources.records.resource  # noqa
    import nr_metadata.documents.resources.records.ui  # noqa
    import nr_metadata.documents.services  # noqa
    import nr_metadata.documents.services.records  # noqa
    import nr_metadata.documents.services.records.config  # noqa
    import nr_metadata.documents.services.records.facets  # noqa
    import nr_metadata.documents.services.records.permissions  # noqa
    import nr_metadata.documents.services.records.schema  # noqa
    import nr_metadata.documents.services.records.search  # noqa
    import nr_metadata.documents.services.records.service  # noqa
    import nr_metadata.documents.services.records.ui_schema  # noqa
    import nr_metadata.documents.version  # noqa
    import nr_metadata.documents.views  # noqa
    import nr_metadata.documents.views.records  # noqa
    import nr_metadata.documents.views.records.api  # noqa
    import nr_metadata.documents.views.records.app  # noqa
    import nr_metadata.schema  # noqa
    import nr_metadata.schema.identifiers  # noqa
    import nr_metadata.ui_schema  # noqa
    import nr_metadata.ui_schema.identifiers  # noqa
    import nr_metadata.ui_schema.subjects  # noqa
