# Generated by Django 3.2.9 on 2021-11-05 15:59

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_public_favicon'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_data', models.JSONField(default=dict, editable=False)),
                ('chip_number', models.IntegerField(verbose_name='Chip Number')),
                ('valid_until', models.DateField(verbose_name='Valid until')),
                ('deactivated', models.BooleanField(default=False, verbose_name='Deactivated')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.person', verbose_name='Person')),
                ('site', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
