
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-13T12:39:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c038963cbd65a7e6cd5b11f26d4e888dbc64d91",
 "version": "1.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
