# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SystemReflectionModule(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assembly': 'SystemReflectionAssembly',
        'fully_qualified_name': 'str',
        'name': 'str',
        'md_stream_version': 'int',
        'module_version_id': 'str',
        'scope_name': 'str',
        'module_handle': 'SystemModuleHandle',
        'custom_attributes': 'list[SystemReflectionCustomAttributeData]',
        'metadata_token': 'int'
    }

    attribute_map = {
        'assembly': 'assembly',
        'fully_qualified_name': 'fullyQualifiedName',
        'name': 'name',
        'md_stream_version': 'mdStreamVersion',
        'module_version_id': 'moduleVersionId',
        'scope_name': 'scopeName',
        'module_handle': 'moduleHandle',
        'custom_attributes': 'customAttributes',
        'metadata_token': 'metadataToken'
    }

    def __init__(self, assembly=None, fully_qualified_name=None, name=None, md_stream_version=None, module_version_id=None, scope_name=None, module_handle=None, custom_attributes=None, metadata_token=None):  # noqa: E501
        """SystemReflectionModule - a model defined in Swagger"""  # noqa: E501
        self._assembly = None
        self._fully_qualified_name = None
        self._name = None
        self._md_stream_version = None
        self._module_version_id = None
        self._scope_name = None
        self._module_handle = None
        self._custom_attributes = None
        self._metadata_token = None
        self.discriminator = None
        if assembly is not None:
            self.assembly = assembly
        if fully_qualified_name is not None:
            self.fully_qualified_name = fully_qualified_name
        if name is not None:
            self.name = name
        if md_stream_version is not None:
            self.md_stream_version = md_stream_version
        if module_version_id is not None:
            self.module_version_id = module_version_id
        if scope_name is not None:
            self.scope_name = scope_name
        if module_handle is not None:
            self.module_handle = module_handle
        if custom_attributes is not None:
            self.custom_attributes = custom_attributes
        if metadata_token is not None:
            self.metadata_token = metadata_token

    @property
    def assembly(self):
        """Gets the assembly of this SystemReflectionModule.  # noqa: E501


        :return: The assembly of this SystemReflectionModule.  # noqa: E501
        :rtype: SystemReflectionAssembly
        """
        return self._assembly

    @assembly.setter
    def assembly(self, assembly):
        """Sets the assembly of this SystemReflectionModule.


        :param assembly: The assembly of this SystemReflectionModule.  # noqa: E501
        :type: SystemReflectionAssembly
        """

        self._assembly = assembly

    @property
    def fully_qualified_name(self):
        """Gets the fully_qualified_name of this SystemReflectionModule.  # noqa: E501


        :return: The fully_qualified_name of this SystemReflectionModule.  # noqa: E501
        :rtype: str
        """
        return self._fully_qualified_name

    @fully_qualified_name.setter
    def fully_qualified_name(self, fully_qualified_name):
        """Sets the fully_qualified_name of this SystemReflectionModule.


        :param fully_qualified_name: The fully_qualified_name of this SystemReflectionModule.  # noqa: E501
        :type: str
        """

        self._fully_qualified_name = fully_qualified_name

    @property
    def name(self):
        """Gets the name of this SystemReflectionModule.  # noqa: E501


        :return: The name of this SystemReflectionModule.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SystemReflectionModule.


        :param name: The name of this SystemReflectionModule.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def md_stream_version(self):
        """Gets the md_stream_version of this SystemReflectionModule.  # noqa: E501


        :return: The md_stream_version of this SystemReflectionModule.  # noqa: E501
        :rtype: int
        """
        return self._md_stream_version

    @md_stream_version.setter
    def md_stream_version(self, md_stream_version):
        """Sets the md_stream_version of this SystemReflectionModule.


        :param md_stream_version: The md_stream_version of this SystemReflectionModule.  # noqa: E501
        :type: int
        """

        self._md_stream_version = md_stream_version

    @property
    def module_version_id(self):
        """Gets the module_version_id of this SystemReflectionModule.  # noqa: E501


        :return: The module_version_id of this SystemReflectionModule.  # noqa: E501
        :rtype: str
        """
        return self._module_version_id

    @module_version_id.setter
    def module_version_id(self, module_version_id):
        """Sets the module_version_id of this SystemReflectionModule.


        :param module_version_id: The module_version_id of this SystemReflectionModule.  # noqa: E501
        :type: str
        """

        self._module_version_id = module_version_id

    @property
    def scope_name(self):
        """Gets the scope_name of this SystemReflectionModule.  # noqa: E501


        :return: The scope_name of this SystemReflectionModule.  # noqa: E501
        :rtype: str
        """
        return self._scope_name

    @scope_name.setter
    def scope_name(self, scope_name):
        """Sets the scope_name of this SystemReflectionModule.


        :param scope_name: The scope_name of this SystemReflectionModule.  # noqa: E501
        :type: str
        """

        self._scope_name = scope_name

    @property
    def module_handle(self):
        """Gets the module_handle of this SystemReflectionModule.  # noqa: E501


        :return: The module_handle of this SystemReflectionModule.  # noqa: E501
        :rtype: SystemModuleHandle
        """
        return self._module_handle

    @module_handle.setter
    def module_handle(self, module_handle):
        """Sets the module_handle of this SystemReflectionModule.


        :param module_handle: The module_handle of this SystemReflectionModule.  # noqa: E501
        :type: SystemModuleHandle
        """

        self._module_handle = module_handle

    @property
    def custom_attributes(self):
        """Gets the custom_attributes of this SystemReflectionModule.  # noqa: E501


        :return: The custom_attributes of this SystemReflectionModule.  # noqa: E501
        :rtype: list[SystemReflectionCustomAttributeData]
        """
        return self._custom_attributes

    @custom_attributes.setter
    def custom_attributes(self, custom_attributes):
        """Sets the custom_attributes of this SystemReflectionModule.


        :param custom_attributes: The custom_attributes of this SystemReflectionModule.  # noqa: E501
        :type: list[SystemReflectionCustomAttributeData]
        """

        self._custom_attributes = custom_attributes

    @property
    def metadata_token(self):
        """Gets the metadata_token of this SystemReflectionModule.  # noqa: E501


        :return: The metadata_token of this SystemReflectionModule.  # noqa: E501
        :rtype: int
        """
        return self._metadata_token

    @metadata_token.setter
    def metadata_token(self, metadata_token):
        """Sets the metadata_token of this SystemReflectionModule.


        :param metadata_token: The metadata_token of this SystemReflectionModule.  # noqa: E501
        :type: int
        """

        self._metadata_token = metadata_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemReflectionModule, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemReflectionModule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
