# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .get_flow_response_compound_document_data_relationships_flow_actions import (
    GetFlowResponseCompoundDocumentDataRelationshipsFlowActions,
)
from .get_flow_response_compound_document_data_relationships_tags import (
    GetFlowResponseCompoundDocumentDataRelationshipsTags,
)


class GetFlowResponseCompoundDocumentDataRelationships(pydantic.BaseModel):
    flow_actions: typing.Optional[GetFlowResponseCompoundDocumentDataRelationshipsFlowActions] = pydantic.Field(
        alias="flow-actions"
    )
    tags: typing.Optional[GetFlowResponseCompoundDocumentDataRelationshipsTags]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        json_encoders = {dt.datetime: serialize_datetime}
