# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .get_segment_retrieve_response_compound_document_data_attributes import (
    GetSegmentRetrieveResponseCompoundDocumentDataAttributes,
)
from .get_segment_retrieve_response_compound_document_data_relationships import (
    GetSegmentRetrieveResponseCompoundDocumentDataRelationships,
)
from .object_links import ObjectLinks
from .segment_enum import SegmentEnum


class GetSegmentRetrieveResponseCompoundDocumentData(pydantic.BaseModel):
    type: typing.Optional[SegmentEnum]
    attributes: typing.Optional[GetSegmentRetrieveResponseCompoundDocumentDataAttributes]
    relationships: typing.Optional[GetSegmentRetrieveResponseCompoundDocumentDataRelationships]
    id: str
    links: ObjectLinks

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
