# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class GetCampaignsRequestIncludeItem(str, enum.Enum):
    CAMPAIGN_MESSAGES = "campaign-messages"
    TAGS = "tags"

    def visit(self, campaign_messages: typing.Callable[[], T_Result], tags: typing.Callable[[], T_Result]) -> T_Result:
        if self is GetCampaignsRequestIncludeItem.CAMPAIGN_MESSAGES:
            return campaign_messages()
        if self is GetCampaignsRequestIncludeItem.TAGS:
            return tags()
