# This file was auto-generated by Fern from our API Definition.

import typing

from .email_content_sub_object import EmailContentSubObject
from .sms_content_sub_object import SmsContentSubObject

PatchCampaignMessageResponseDataAttributesContent = typing.Union[EmailContentSubObject, SmsContentSubObject]
