# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.6.7
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

from py-scibec-openapi-client.paths.functional_accounts_count.get import FunctionalAccountControllerCount
from py-scibec-openapi-client.paths.functional_accounts.post import FunctionalAccountControllerCreate
from py-scibec-openapi-client.paths.functional_accounts_id.delete import FunctionalAccountControllerDeleteById
from py-scibec-openapi-client.paths.functional_accounts.get import FunctionalAccountControllerFind
from py-scibec-openapi-client.paths.functional_accounts_id.get import FunctionalAccountControllerFindById
from py-scibec-openapi-client.paths.functional_accounts.patch import FunctionalAccountControllerUpdateAll
from py-scibec-openapi-client.paths.functional_accounts_id.patch import FunctionalAccountControllerUpdateById


class FunctionalAccountControllerApi(
    FunctionalAccountControllerCount,
    FunctionalAccountControllerCreate,
    FunctionalAccountControllerDeleteById,
    FunctionalAccountControllerFind,
    FunctionalAccountControllerFindById,
    FunctionalAccountControllerUpdateAll,
    FunctionalAccountControllerUpdateById,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
