
ALPHAVANTAGE = 'ALPHAVANTAGE'
FINNHUB = 'FINNHUB'
FMP = 'FMP'
QUANDL = 'QUANDL'

ALL_EXCHANGES = 'ALL_EXCHANGES'
EXCHANGES_LIST = [ALPHAVANTAGE, QUANDL, FINNHUB, FMP]

POSTGRES = 'POSTGRES'
REDIS = 'REDIS'

# REST OP
GET = 'GET'
POST = 'POST'

# available methods / tables
REFRESH_SYMBOL = 'REFRESH_SYMBOL'
REFRESH_SYMBOL_LOOKUP = 'REFRESH_SYMBOL_LOOKUP'
REFRESH_SYMBOL_PEERS = 'REFRESH_SYMBOL_PEERS'
REFRESH_SYMBOL_GAINERS_LOSERS = 'REFRESH_SYMBOL_GAINERS_LOSERS'

SYMBOL_FLOW = 'SYMBOL_FLOW'
SYMBOL_LOOKUP_FLOW = 'SYMBOL_LOOKUP_FLOW'
SYMBOL_PEERS_FLOW = 'SYMBOL_PEERS_FLOW'
SYMBOL_GAINERS_LOSERS_FLOW = 'SYMBOL_GAINERS_LOSERS_FLOW'

GAINERS = 'GAINERS'
LOSERS = 'LOSERS'

# alphavantage apis
AV_SYMBOL = 'AV_SYMBOL'
AV_SYMBOL_SEARCH = 'AV_SYMBOL_SEARCH'
AV_OVERVIEW = 'AV_OVERVIEW'
AV_GAINERS_LOSERS = 'AV_GAINERS_LOSERS'

# finnhub apis
FH_SYMBOL = 'FH_SYMBOL'
FH_PROFILE = 'FH_PROFILE'
FH_PEERS = 'FH_PEERS'

# fmp apis
FMP_SYMBOL = 'FMP_SYMBOL'
FMP_GAINERS = 'FMP_GAINERS'
FMP_LOSERS = 'FMP_LOSERS'


SYMBOL = 'SYMBOL'
EXCHANGE = 'EXCHANGE'
BASE_SYMBOL = 'BASE_SYMBOL'
QUOTE_SYMBOL = 'QUOTE_SYMBOL'
NAME = 'NAME'
TYPE = 'TYPE'
DESCRIPTION = 'DESCRIPTION'
SYMBOL_EXCHANGE = 'SYMBOL_EXCHANGE'
CIK = 'CIK'
COUNTRY = 'COUNTRY'
SECTOR = 'SECTOR'
INDUSTRY = 'INDUSTRY'
ADDRESS = 'ADDRESS'
IPO = 'IPO'
PHONE = 'PHONE'
WEBSITE = 'WEBSITE'
LOGO = 'LOGO'
SYMBOL_LOOKUP = 'SYMBOL_LOOKUP'
SYMBOL_PEERS = 'SYMBOL_PEERS'
MOVEMENT = 'MOVEMENT'
SYMBOL_GAINERS_LOSERS = 'SYMBOL_GAINERS_LOSERS'

SUBSCRIPTION = 'SUBSCRIPTION'
SYNC_SUBSCRIPTION = 'SYNC_SUBSCRIPTION'
SYNC_SUBSCRIPTION_DEL = 'SYNC_SUBSCRIPTION_DEL'

SYMBOL_OVERVIEW_SUBSCRIPTION = 'SYMBOL_OVERVIEW_SUBSCRIPTION'
SYNC_SYMBOL_OVERVIEW_SUBSCRIPTION = 'SYNC_SYMBOL_OVERVIEW_SUBSCRIPTION'



RAW = 'RAW'
CONNECTION = 'CONNECTION'
EXCHANGE = 'EXCHANGE'
API = 'API'


# db schema
TABLE = 'tb_'
VIEW = 'vw_'
