"""Quick and easy documentation and hosting for OpenRPC APIs."""
__all__ = (
    "get_app",
    "Components",
    "Contact",
    "ContentDescriptor",
    "Error",
    "Example",
    "ExamplePairing",
    "ExternalDocumentation",
    "Info",
    "License",
    "Link",
    "Method",
    "OpenRPC",
    "ParamStructure",
    "RPCRouter",
    "RPCServer",
    "Reference",
    "Schema",
    "SchemaType",
    "Server",
    "ServerVariable",
    "Tag",
    "Depends",
)

from openrpc import (
    Components,
    Contact,
    ContentDescriptor,
    Error,
    Example,
    ExamplePairing,
    ExternalDocumentation,
    Info,
    License,
    Link,
    Method,
    OpenRPC,
    ParamStructure,
    RPCRouter,
    RPCServer,
    Reference,
    Schema,
    SchemaType,
    Server,
    ServerVariable,
    Tag,
    Depends,
)

from tabella._app import get_app
