# Generated by Django 4.2.4 on 2023-08-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_data_import_management', '0005_auto_20201211_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangodataimportitem',
            name='import_success',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Import Success'),
        ),
        migrations.AlterField(
            model_name='djangodataimportitem',
            name='success',
            field=models.BooleanField(blank=True, null=True, verbose_name='Parse Success'),
        ),
    ]
