
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-13T04:21:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1cbb17624e9cd7eb12fdea67ac94c1d724d528c",
 "version": "1.18.4.post0.dev200"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
