# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethermint/feemarket/v1/feemarket.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethermint/feemarket/v1/feemarket.proto',
  package='ethermint.feemarket.v1',
  syntax='proto3',
  serialized_options=b'\n\032com.ethermint.feemarket.v1B\016FeemarketProtoP\001Z,github.com/evmos/ethermint/x/feemarket/types\242\002\003EFX\252\002\026Ethermint.Feemarket.V1\312\002\026Ethermint\\Feemarket\\V1\342\002\"Ethermint\\Feemarket\\V1\\GPBMetadata\352\002\030Ethermint::Feemarket::V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&ethermint/feemarket/v1/feemarket.proto\x12\x16\x65thermint.feemarket.v1\x1a\x14gogoproto/gogo.proto\"\xd6\x03\n\x06Params\x12\x1e\n\x0bno_base_fee\x18\x01 \x01(\x08R\tnoBaseFee\x12=\n\x1b\x62\x61se_fee_change_denominator\x18\x02 \x01(\rR\x18\x62\x61seFeeChangeDenominator\x12\x33\n\x15\x65lasticity_multiplier\x18\x03 \x01(\rR\x14\x65lasticityMultiplier\x12#\n\renable_height\x18\x05 \x01(\x03R\x0c\x65nableHeight\x12I\n\x08\x62\x61se_fee\x18\x06 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.IntR\x07\x62\x61seFee\x12R\n\rmin_gas_price\x18\x07 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecR\x0bminGasPrice\x12\\\n\x12min_gas_multiplier\x18\x08 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecR\x10minGasMultiplierJ\x04\x08\x04\x10\x05R\x10initial_base_feeB\xd4\x01\n\x1a\x63om.ethermint.feemarket.v1B\x0e\x46\x65\x65marketProtoP\x01Z,github.com/evmos/ethermint/x/feemarket/types\xa2\x02\x03\x45\x46X\xaa\x02\x16\x45thermint.Feemarket.V1\xca\x02\x16\x45thermint\\Feemarket\\V1\xe2\x02\"Ethermint\\Feemarket\\V1\\GPBMetadata\xea\x02\x18\x45thermint::Feemarket::V1b\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='ethermint.feemarket.v1.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='no_base_fee', full_name='ethermint.feemarket.v1.Params.no_base_fee', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='noBaseFee', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_fee_change_denominator', full_name='ethermint.feemarket.v1.Params.base_fee_change_denominator', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='baseFeeChangeDenominator', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='elasticity_multiplier', full_name='ethermint.feemarket.v1.Params.elasticity_multiplier', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='elasticityMultiplier', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_height', full_name='ethermint.feemarket.v1.Params.enable_height', index=3,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='enableHeight', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_fee', full_name='ethermint.feemarket.v1.Params.base_fee', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Int', json_name='baseFee', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_gas_price', full_name='ethermint.feemarket.v1.Params.min_gas_price', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec', json_name='minGasPrice', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_gas_multiplier', full_name='ethermint.feemarket.v1.Params.min_gas_multiplier', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec', json_name='minGasMultiplier', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=559,
)

DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'ethermint.feemarket.v1.feemarket_pb2'
  # @@protoc_insertion_point(class_scope:ethermint.feemarket.v1.Params)
  })
_sym_db.RegisterMessage(Params)


DESCRIPTOR._options = None
_PARAMS.fields_by_name['base_fee']._options = None
_PARAMS.fields_by_name['min_gas_price']._options = None
_PARAMS.fields_by_name['min_gas_multiplier']._options = None
# @@protoc_insertion_point(module_scope)
