
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-08T02:36:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3dc4f04f5c3848ccd819539fc813152e9cea268",
 "version": "v0.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
